language: c

compiler: gcc

sudo: require

service:
  - docker

git:
  depth: false

## NOTIFICATIONS
notifications:
  email:
    recipients:
    - florent.poinsard@epitech.eu
    - cecile.cadoul@epitech.eu
    on_success: never
    on_failure: always
  slack: epitech-tls-22:hI5SZsYgJjCuI9iL801FQoam

jobs:
    include :
        - stage: build
          name: "Build"
          install:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && make fclean && make"

        - stage: tests
          name: "Unit Tests"
          install:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && make tests_run_coverage"
          after_script:
            - bash <(curl -s https://codecov.io/bash) || echo "Codecov - Coverage error."
        -
          name: "Functional Tests"
          if: branch IN (master, dev, tests, travis)
          before_script:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && make tests_functional || echo no functional test yet"

        - stage: deploy
          name: "Deployement"
          if: branch IN (master, travis) AND type != cron AND type != pull_request
          before_script:
            - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
            - git checkout $TRAVIS_BRANCH
          script:
            - git push --repo=git@git.epitech.eu:/florent.poinsard@epitech.eu/OOP_nanotekspice_2018 --force
